name: example
description: Example project using slang.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  slang:
    path: ../
  slang_flutter:
    path: ../../slang_flutter/
  flutter_localizations: # add this
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
#  build_runner: any
#  slang_build_runner: any

flutter:
  uses-material-design: true