name: slang_build_runner
description: build_runner integration for slang. This library ensures that slang is recognized by build_runner.
version: 4.9.0
repository: https://github.com/slang-i18n/slang

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  build: '>=2.2.1 <5.0.0'
  dart_style: '>=2.3.7 <4.0.0'
  glob: ^2.0.2

  # Use a tight version to ensure that all features are available
  slang: '>=4.9.0 <4.10.0'

dev_dependencies:
  lints: any
