name: slang_build_runner
description: build_runner integration for slang. This library ensures that slang is recognized by build_runner.
version: 4.4.1
repository: https://github.com/slang-i18n/slang

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  build: ^2.2.1
  dart_style: '>=2.3.0 <4.0.0'
  glob: ^2.0.2

  # Use a tight version to ensure that all features are available
  slang: '>=4.4.0 <4.5.0'

dev_dependencies:
  lints: any
