name: slang_build_runner
description: build_runner integration for slang. This library ensures that slang is recognized by build_runner.
version: 3.13.0
repository: https://github.com/Tienisto/slang

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^2.2.1
  glob: ^2.0.2

  # Use tight version to ensure that all features are available
  slang: '>=3.13.0 <3.14.0'
