name: fast_i18n
description: Localization / Internationalization (i18n) solution. Use JSON, YAML or CSV files to create typesafe translations via source generation.
version: 5.12.3
repository: https://github.com/Tienisto/flutter-fast-i18n

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.2.1
  collection: ^1.15.0
  csv: ^5.0.1
  glob: ^2.0.2
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.6
  test: ^1.16.8
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

