name: slang_flutter
description: Flutter support for slang. This library provides helpful Flutter API.
version: 3.6.0
repository: https://github.com/Tienisto/slang

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use tight version to ensure that all features are available
  slang: '>=3.6.0 <3.7.0'
