name: slang_flutter
description: Flutter support for slang. This library provides helpful Flutter API.
version: 3.28.0
repository: https://github.com/slang-i18n/slang

environment:
  flutter: '>=3.0.0'
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use a tight version to ensure that all features are available
  slang: '>=3.28.0 <3.29.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
