name: slang_gpt
description: Use GPT to automatically translate at compile time. A tool for slang.
version: 0.11.0
repository: https://github.com/slang-i18n/slang

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  http: '>=0.13.0 <2.0.0'
  slang: '>=4.0.0 <5.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
