name: slang_mcp
description: An MCP server for slang to allow working with LLMs more efficiently.
version: 0.1.0
repository: https://github.com/slang-i18n/slang

environment:
  sdk: ^3.3.0

executables:
  slang_mcp:

dependencies:
  mcp_dart: ^1.2.2
  slang: '>=4.12.0 <5.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
