# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION_OLDEST: "3.0.5"
  FLUTTER_VERSION_NEWEST: "3.19.2"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_NEWEST }}
          channel: "stable"

      - name: Dependencies (core)
        working-directory: slang
        run: dart pub get
      - name: Check format (core)
        working-directory: slang
        run: dart format --set-exit-if-changed lib bin test
      - name: Analyze (core)
        working-directory: slang
        run: flutter analyze

      - name: Dependencies (gpt)
        working-directory: slang_gpt
        run: dart pub get
      - name: Check format (gpt)
        working-directory: slang_gpt
        run: dart format --set-exit-if-changed lib bin test
      - name: Analyze (gpt)
        working-directory: slang_gpt
        run: flutter analyze

  test:
    name: Test (newest Flutter version)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_NEWEST }}
          channel: "stable"

      - name: Dependencies (flutter)
        working-directory: slang_flutter
        run: flutter pub get
      - name: Test (flutter)
        working-directory: slang_flutter
        run: flutter test

      # The compilation test needs "pub get" to be run for Flutter first.
      # That's why we run the core tests after the Flutter tests.
      - name: Dependencies (core)
        working-directory: slang
        run: dart pub get
      - name: Test (core)
        working-directory: slang
        run: dart test

      - name: Dependencies (gpt)
        working-directory: slang_gpt
        run: dart pub get
      - name: Test (gpt)
        working-directory: slang_gpt
        run: dart test

  test_legacy:
    name: Test (oldest Flutter version)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION_OLDEST }}
          channel: "stable"

      - name: Dependencies (flutter)
        working-directory: slang_flutter
        run: flutter pub get
      - name: Test (flutter)
        working-directory: slang_flutter
        run: flutter test

      # The compilation test needs "pub get" to be run for Flutter first.
      # That's why we run the core tests after the Flutter tests.
      - name: Dependencies (core)
        working-directory: slang
        run: dart pub get
      - name: Test (core)
        working-directory: slang
        run: dart test

      - name: Dependencies (gpt)
        working-directory: slang_gpt
        run: dart pub get
      - name: Test (gpt)
        working-directory: slang_gpt
        run: dart test
